# Generated by Django 2.2.6 on 2019-10-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MvInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('performer_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('name_in_code', models.CharField(max_length=50)),
                ('mv_id', models.CharField(default='Enter ID here', max_length=15)),
                ('embed_link', models.CharField(default='Enter embed link here', max_length=350)),
                ('is_disabled', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
