# Generated by Django 2.2.6 on 2019-10-24 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stream_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvinfo',
            name='date_of_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mvinfo',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
