# Generated by Django 2.2.6 on 2019-10-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_service', '0003_auto_20191024_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvinfo',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
