# Generated by Django 2.2.6 on 2019-10-27 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stream_service', '0004_mvinfo_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('name_in_code', models.CharField(max_length=50)),
                ('show_id', models.CharField(default='Enter ID here', max_length=15)),
                ('embed_link', models.CharField(default='Enter embed link here', max_length=350)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_disabled', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_of_update', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
