# Generated by Django 2.2.6 on 2019-11-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_service', '0007_showepisode_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinfo',
            name='small_info',
            field=models.CharField(default='Enter added info', max_length=100),
        ),
    ]
