# Generated by Django 2.2.6 on 2019-11-02 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream_service', '0008_showinfo_small_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showepisode',
            name='show',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='stream_service.ShowInfo'),
        ),
    ]
