# Generated by Django 2.2.6 on 2019-11-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_service', '0009_auto_20191102_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinfo',
            name='title_in_japanese',
            field=models.CharField(default='なし', max_length=30),
        ),
    ]
