# Generated by Django 2.2.6 on 2019-11-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_service', '0010_showinfo_title_in_japanese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showepisode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='showepisode',
            name='episode_id',
        ),
        migrations.RemoveField(
            model_name='showepisode',
            name='name_in_code',
        ),
        migrations.RemoveField(
            model_name='showepisode',
            name='view_count',
        ),
    ]
