# Generated by Django 2.2.6 on 2019-11-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_service', '0011_auto_20191106_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='showepisode',
            name='video_duration',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
    ]
