# Generated by Django 2.2.6 on 2019-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_service', '0012_showepisode_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='showepisode',
            name='episode_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
